### ISSUE TITLE
No french translation

### ISSUE THREAD

**Issue by LeMoussel** [trilbymedia/grav-plugin-tntsearch#100]
Hi,

in [languages.yaml](https://github.com/trilbymedia/grav-plugin-tntsearch/blob/develop/languages.yaml) there is no translation for French. I propose the following translation for French:
```
fr:
  PLUGIN_TNTSEARCH:
    FOUND_RESULTS: "Résultats trouvés: %s"
    FOUND_IN: "(<span>%s</span>)"
    POWERED_BY: "Par %s"
```
