### ISSUE TITLE
Indexing Modular and Custom Field Content with Flex Pages

### ISSUE THREAD

**Issue by thekenshow** [trilbymedia/grav-plugin-tntsearch#102]
I'm not able to get modular and custom field content indexed with Flex Pages enabled, despite creating a template as explained in the docs. 

I have a modular page with a few modules that use a custom blueprint:
```
modular.en.md
    infolist.en.md
    infolist.en.md
    infolist.en.md
```

The following YAML appears in `modular.en.md`:

```
content:
    items: '@self.modular'
``` 

The module page content in `infolist.en.md` looks like this:

```
<p>We are the XYZ experts, from a very-unique-word and more.</p>
```

The modular page custom field content in `infolist.en.md` looks like this:

```
listitems:
    -
        itemtitle: Something
        itemimage: someimage.jpg
        itemimageloc: center
        itemicon: null
        itemiconloc: null
        itemdesc: '<p>A bit of text with another-very-unique-word in it.</p>'
```

I've created a `templates/tntsearch/modular.html.twig` file to capture modular and custom field content:

```
{% for module in page.collection() %}
<p>
    {{ module.content }}
    {% for info in module.listitems %}
      {{ info.itemtitle }}
      {{ info.itemdesc }}
    {% endfor %}
</p>
{% endfor %}

{{ page.content }}
```

When I index the site, I get only the parent `modular.en.md` page content, and nothing from the `infolist.en.md` module page content or custom field.

Could this be related to the lack of Flex Page support for `@self` in blueprints as noted at [Page Blueprint with filepicker field does not recognize folder value of @self](https://github.com/trilbymedia/grav-plugin-flex-objects/issues/71)?

**Comment by mahagr** [comment]
The `@self` issue in filepicker should be separate to this one (upload handling was missing support for it); modular pages should work just like they do with the regular pages.

I need to take a look what's going on here...

**Comment by thekenshow** [comment]
OK, let me know if you need more information.

**Comment by mahagr** [comment]
You are missing:

```
tntsearch:
  template: 'tntsearch/modular.html.twig'
content:
    items: '@self.modular'
```
