### ISSUE TITLE
Irregular results

### ISSUE THREAD

**Issue by stell** [trilbymedia/grav-plugin-tntsearch#114]
Everything is up to date and freshly indexed. I have two pages containing the word "geokoordinaten" which is German and stands for Geocoordinates.

When searching for "geokoordinaten" i get 2 results, which is correct.

"geokoordina" outputs 0 results.
"geokoo" outputs 2 results again.

I don't know if this is an issue or something is badly setup, but i don't see whats the problem here.

You can try it out here:
[https://www.jfewo.de/docs/de/suche?q=geokoordinaten](https://www.jfewo.de/docs/de/suche?q=geokoordinaten)

This is the config:

```
enabled: true
search_route: /suche
query_route: /s
built_in_css: true
built_in_js: true
built_in_search_page: true
enable_admin_page_events: true
search_type: auto
fuzzy: false
phrases: true
stemmer: german
display_route: true
display_hits: true
display_time: true
live_uri_update: true
limit: "20"
min: "4"
snippet: "300"
index_page_by_default: true
scheduled_index:
  enabled: false
  at: "* 2 * * 1-7"
  logs: logs/tntsearch-index.out
filter:
  items:
    - root@.descendants
powered_by: true
search_object_type: Grav

```

**Comment by nqb** [comment]
Hello,

I noticed same kind of issue on [YunoHost's documentation](https://yunohost.org/en/search?q=).
If I search for "revers", I got 5 pages with "reverse" or "Reverse" results but if I add a "e" (for "reverse"), I got only one result.

**Comment by ViliusS** [comment]
> Everything is up to date and freshly indexed. I have two pages containing the word "geokoordinaten" which is German and stands for Geocoordinates.
> 
> When searching for "geokoordinaten" i get 2 results, which is correct.
> 
> "geokoordina" outputs 0 results.
> "geokoo" outputs 2 results again.
> 
> On the other hand if searching for "geoko" i get 2 results again, but different pages. Should this not output 4 pages?
> 
> I don't know if this is an issue or something is badly setup, but i don't see whats the problem here.
> 
> You can try it out here:
> https://www.jfewo.de/docs/de/suche?q=geokoordinaten
> 
> This is the config:
> 
> ```
> enabled: true
> search_route: /suche
> query_route: /s
> built_in_css: true
> built_in_js: true
> built_in_search_page: true
> enable_admin_page_events: true
> search_type: auto
> fuzzy: false
> phrases: true
> stemmer: german
> display_route: true
> display_hits: true
> display_time: true
> live_uri_update: true
> limit: "20"
> min: "4"
> snippet: "300"
> index_page_by_default: true
> scheduled_index:
>   enabled: false
>   at: "* 2 * * 1-7"
>   logs: logs/tntsearch-index.out
> filter:
>   items:
>     - root@.descendants
> powered_by: true
> search_object_type: Grav
> ```

Try disabling the stemmer and rebuilding the index after that. See if that helps.

**Comment by stell** [comment]
Already tried that. Same irregular results.

**Comment by ViliusS** [comment]
Just tried your link ant it shows 2 same results for "geokoordina" and "geokoo".

**Comment by stell** [comment]
Cannot confirm. 
"geokoordina" outputs 0 results
"geokoo" outputs 2 results
"geoko"  outputs 2 (different) results

In fact all of this should output more that 2 results.

**Comment by ViliusS** [comment]
I don't know enough about German language but the difference between "geokoordina" and "geokoordinat" looks like really a stemmer issue. Setting stemmer to 'no' should return the same results for both queries.

**Comment by stell** [comment]
Yeah, I thought the same.

**Comment by ViliusS** [comment]
Without stemmer:

`[]# php -r " include('Stemmer.php'); require_once ('NoStemmer.php'); echo TeamTNT\TNTSearch\Stemmer\NoStemmer::stem('geokoordina').PHP_EOL;"`
geokoordina

`[]# php -r " include('Stemmer.php'); require_once ('NoStemmer.php'); echo TeamTNT\TNTSearch\Stemmer\NoStemmer::stem('geokoordinat').PHP_EOL;"`
geokoordinat

`[]# php -r " include('Stemmer.php'); require_once ('NoStemmer.php'); echo TeamTNT\TNTSearch\Stemmer\NoStemmer::stem('geokoordinaten').PHP_EOL;"`
geokoordina**ten**

With stemmer:
`[]# php -r " include('Stemmer.php'); require_once ('GermanStemmer.php'); echo TeamTNT\TNTSearch\Stemmer\GermanStemmer::stem('geokoordina').PHP_EOL;"`
geokoordina

`[]# php -r " include('Stemmer.php'); require_once ('GermanStemmer.php'); echo TeamTNT\TNTSearch\Stemmer\GermanStemmer::stem('geokoordinat').PHP_EOL;"`
geokoordinat

`[]# php -r " include('Stemmer.php'); require_once ('GermanStemmer.php'); echo TeamTNT\TNTSearch\Stemmer\GermanStemmer::stem('geokoordinaten').PHP_EOL;"`
geokoordina**t**

Check if you really disabled the stemmer, i.e. set it to 'no', because at least the last difference is a stemmer issue. Stemming is a complex beast, so to properly debug issue I would disable it for now.

**Comment by stell** [comment]
Like I said. I tested it without stemmer at the beginning and two more times after. Results are the same.

**Comment by mbirth** [comment]
Same here:

![Screenshot 2021-07-19 at 12 31 54](https://user-images.githubusercontent.com/130302/126147008-49fe71b5-2b6e-438e-8275-b0f9756a49a3.png)

But if I add the final "e", I get no results:

![Screenshot 2021-07-19 at 12 32 01](https://user-images.githubusercontent.com/130302/126147046-b28d80f0-94af-4ff8-904e-9923add0ef74.png)

My config:

```yaml
enabled: true
search_route: /search
query_route: /s
built_in_css: true
built_in_js: true
built_in_search_page: true
enable_admin_page_events: true
search_type: auto
fuzzy: true
phrases: true
stemmer: "no"
display_route: true
display_hits: true
display_time: true
live_uri_update: true
limit: '20'
min: '3'
snippet: '300'
index_page_by_default: true
scheduled_index:
  enabled: false
  at: '30 3 * * *'
  logs: logs/tntsearch-index.out
filter:
  items:
    - root@.descendants
  published: true
powered_by: false
search_object_type: Grav
```

PHP:

```
PHP 7.4.21 (cli) (built: Jun 29 2021 15:17:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.21, Copyright (c), by Zend Technologies
```

Grav and TNTSearch are up to date.
