### ISSUE TITLE
Search Filter field placeholder is wrong

### ISSUE THREAD

**Issue by drnasin** [trilbymedia/grav-plugin-tntsearch#17]
as the title says. if I take the format from README than it works. So maybe an update to reflect this:
```
filter:
  items:
    taxonomy@:
      category: [docs]
```
and this generates the following yaml in search field:

`
taxonomy@: { category: [docs] }`
