### ISSUE TITLE
Tokenizer can't handle arrays in frontmatter

### ISSUE THREAD

**Issue by nicolasconnault** [trilbymedia/grav-plugin-tntsearch#31]
If you have custom array structures in your page frontmatter, TNTSearch's Tokenizer class throws a fatal PHP error when doing mb_strtolower($text).

The solution is to detect if $text is an array, and serialize it in that case (implode doesn't work because the array may also contain arrays).

**Comment by rhukster** [comment]
Can you provide me with some sample frontmatter?  I've got some fairly custom structure and it's not tripping it up.

**Comment by nicolasconnault** [comment]
Sorry I haven't used Grav for a while now, my next projects are all using Craft CMS :)

**Comment by dimitrilongo** [comment]
hi,
i reopen that issue cause I found array structure that cause fatal error. from `list`field
example : 
````
author:
    -
        name: 'Dimitri Longo'
        avatar: dimitri-longo.jpg
        description: 'Lorem Lipsum'
        items:
            -
                social: twitter
                url: '#'
                title: Twitter
            -
                social: facebook
                url: '#'
                title: Facebook
            -
                social: slack
                url: '#'
                title: Slack
            -
                social: github
                url: '#'
                title: Github
    -
        name: 'Jack Slater'
        avatar: photo-jack-slater-portrait.jpg
        description: 'Lorem Lipsum'
        items:
            -
                social: twitter
                url: '#'
                title: Twitter
            -
                social: facebook
                url: '#'
                title: Facebook
            -
                social: linkedin
                url: '#'
                title: LinkedIn
````
