### ISSUE TITLE
Tokenizer can't handle arrays in frontmatter

### ISSUE THREAD

**Issue by dimitrilongo** [trilbymedia/grav-plugin-tntsearch#60]
hi,
i reopen that issue :
https://github.com/trilbymedia/grav-plugin-tntsearch/issues/31 cause I found array structure that cause fatal error. from nested `list`field

As @nicolasconnault said

> If you have custom array structures in your page frontmatter, TNTSearch's Tokenizer class throws a fatal PHP error when doing mb_strtolower($text).
> The solution is to detect if $text is an array, and serialize it in that case (implode doesn't work because the array may also contain arrays).

example : 
````
author:
    -
        name: 'Dimitri Longo'
        avatar: dimitri-longo.jpg
        description: 'Lorem Lipsum'
        items:
            -
                social: twitter
                url: '#'
                title: Twitter
            -
                social: facebook
                url: '#'
                title: Facebook
            -
                social: slack
                url: '#'
                title: Slack
            -
                social: github
                url: '#'
                title: Github
    -
        name: 'Jack Slater'
        avatar: photo-jack-slater-portrait.jpg
        description: 'Lorem Lipsum'
        items:
            -
                social: twitter
                url: '#'
                title: Twitter
            -
                social: facebook
                url: '#'
                title: Facebook
            -
                social: linkedin
                url: '#'
                title: LinkedIn
````

**Comment by rhukster** [comment]
I'm a bit confused by this issue because by default, the TNTSearch plugin only indexes the `$page->header()` and `$page->content()`.  

So are you trying to index a custom header element yourself with the `onTNTSearchIndex(Event $e)` event? If so isn't that something you should handle in that event?  Am I missing something?

BTW,  I dropped this example frontmatter into a test page and it indexed with the default plugin just fine.

**Comment by dimitrilongo** [comment]
no I'm not using for the test `onTNTSearchIndex(Event $e)` , when using it for a custom header element I handle `array`. But I disable that plugin and the `fatal error` still here, when I remove that nested `list` field no more fatal error.
this is my TNT conf

````
enabled: true
search_route: /search
query_route: /s
built_in_css: false
built_in_js: true
built_in_search_page: true
enable_admin_page_events: true
search_type: auto
fuzzy: false
phrases: true
stemmer: default
display_route: false
display_hits: true
display_time: false
live_uri_update: false
limit: '20'
min: '3'
snippet: '250'
index_page_by_default: true
filter:
  items:
    - '@root.descendants'
powered_by: false
search_object_type: Grav
````

I tested again with a brand new default page with my nested list, error here

**Comment by rhukster** [comment]
Can you turn on the full errors and show me a screen shot of the exception you get?

**Comment by dimitrilongo** [comment]
Full error Exception
![capture d ecran 2018-10-29 a 19 27 29](https://user-images.githubusercontent.com/3842190/47672283-e0ae1700-dbb1-11e8-8a88-dd7672316d2e.png)

**Comment by rhukster** [comment]
and what does the whole page .md file look like for this page?

**Comment by dimitrilongo** [comment]
````
---
title: 'test AMP'
author:
    -
        name: 'Dimitri Longo'
        avatar: dimitri-longo.jpg
        description: 'Lorem Lipsum'
        items:
            -
                social: twitter
                url: '#'
                title: Twitter
            -
                social: facebook
                url: '#'
                title: Facebook
            -
                social: slack
                url: '#'
                title: Slack
            -
                social: github
                url: '#'
                title: Github
    -
        name: 'Jack Slater'
        avatar: photo-jack-slater-portrait.jpg
        description: 'Lorem Lipsum'
        items:
            -
                social: twitter
                url: '#'
                title: Twitter
            -
                social: facebook
                url: '#'
                title: Facebook
            -
                social: linkedin
                url: '#'
                title: LinkedIn
---

````
