### ISSUE TITLE
Custom search class

### ISSUE THREAD

**Issue by fosil** [trilbymedia/grav-plugin-tntsearch#62]
Hi
I would very much like to set my own class for custom search method.
For example, I need to solve the problem that the standard TNTSearch class uses the contain rule "string%" and not "% string%".
Implementation would be very simple:

In blueprints.yaml add one field for class path:
```
search_class:
        type: text
        label: Custom search class
        help: Full class path for Custom search type option (optional extend from \TeamTNT\TNTSearch\TNTSearch)
```

and in classes/GravTNTSearch.php:

- remove line
```
use TeamTNT\TNTSearch\TNTSearch;
```

- add line (after `$search_type = Grav::instance()['config']->get('plugins.tntsearch.search_type', 'auto');`)
```
$search_class = Grav::instance()['config']->get('plugins.tntsearch.search_class', '\TeamTNT\TNTSearch\TNTSearch');
```
- and change line: `$this->tnt = new TNTSearch();` to
```
$this->tnt = new $search_class;
```

That's enough
Thx
